version: '3'
services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: cod1serverlast
    #container_name: cod1_server
    restart: unless-stopped
    ports:
      - "20500:20500/udp"
      - "20510:20510/udp"
      - "20010:28960/tcp"
      - "20010:28960/udp"
    command: [
        "./cod_lnxded", # DONT CHANGE THIS
        "+set net_ip localhost", # DONT CHANGE THIS
        "+set net_port 28960", # DONT CHANGE THIS
        "+exec myserver.cfg",
        "+map mp_harbor",
#        "+map_rotate",
      ]
    tty: true
    volumes:
       - ./:/data/myserver/
    networks:
      - server-network

networks:
  server-network:
    driver: bridge
